// app/api/referrals/activate/route.js
//
// POST /api/referrals/activate
// Body: { email }
//
// First step for anyone who wants to become a referrer: creates (or
// reuses) a `referrers` doc and a Didit KYC session for THEM. Referrers
// must complete their own KYC before they can generate a referral code —
// see src/lib/referrals.js's header comment for why (self-referral
// blocking needs a verified identity on both sides of a referral).
//
// Returns the Didit session url so the frontend can redirect/embed the
// referrer's own verification. The referral code itself isn't issued
// here — it's generated by the webhook once this session comes back Approved.

import { NextResponse } from "next/server";
import { createDiditSession } from "../../../../lib/didit.js";
import { getReferralCollections, ensureReferralIndexes, normalizeEmail, isValidEmail } from "../../../../lib/referrals.js";

export async function POST(req) {
  try {
    const { email: rawEmail } = await req.json();
    const email = normalizeEmail(rawEmail);
    if (!email || !isValidEmail(email)) {
      return NextResponse.json({ error: "A valid email is required." }, { status: 400 });
    }

    await ensureReferralIndexes();
    const { referrers } = await getReferralCollections();

    const existing = await referrers.findOne({ email });
    if (existing?.status === "verified") {
      return NextResponse.json({ status: "verified", referralCode: existing.referralCode });
    }

    // Reuse an existing pending session rather than spawning a new Didit
    // session on every retry/page-refresh.
    if (existing?.status === "pending" && existing.diditSessionUrl) {
      return NextResponse.json({ status: "pending", url: existing.diditSessionUrl });
    }

    const now = new Date().toISOString();
    await referrers.updateOne(
      { email },
      { $setOnInsert: { email, status: "pending", successfulReferralCount: 0, createdAt: now } },
      { upsert: true }
    );
    const referrerDoc = await referrers.findOne({ email });

    const session = await createDiditSession({ vendorData: `activation:${referrerDoc._id.toString()}` });

    await referrers.updateOne(
      { _id: referrerDoc._id },
      { $set: { diditSessionId: session.sessionId, diditSessionUrl: session.url, status: "pending", updatedAt: now } }
    );

    return NextResponse.json({ status: "pending", url: session.url });
  } catch (err) {
    console.error("referrals/activate failed:", err);
    return NextResponse.json({ error: "Could not start verification. Please try again." }, { status: 500 });
  }
}
