// app/api/orgs/nas/shares/[shareId]/snapshot-policy/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getSnapshotPolicy, setSnapshotPolicy } from "../../../../../../../lib/nas/snapshots.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getSnapshotPolicy({ orgId, shareId: params.shareId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setSnapshotPolicy({ orgId, shareId: params.shareId, intervalMinutes: body.intervalMinutes, keepLast: body.keepLast, immutable: body.immutable, retentionDays: body.retentionDays, enabled: body.enabled, membership, actorEmail: email }));
