// app/api/orgs/nas/shares/[shareId]/quota/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getShareCapacity } from "../../../../../../../lib/nas/quotas.js";
import { quotaAction } from "../../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getShareCapacity({ orgId, shareId: params.shareId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => quotaAction({ orgId, shareId: params.shareId, body, membership, actorEmail: email }));
