// app/api/orgs/nas/appliances/[applianceId]/overview/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getOverview } from "../../../../../../../lib/nas/health.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getOverview({ orgId, applianceId: params.applianceId, membership }));
