// app/api/orgs/nas/cloud-targets/[targetId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { deleteCloudTarget, testCloudTarget } from "../../../../../../lib/nas/cloudTargets.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => testCloudTarget({ orgId, targetId: params.targetId, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => deleteCloudTarget({ orgId, targetId: params.targetId, membership }));
