// app/api/orgs/nas/shares/[shareId]/tiering/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { listTieringProposals, proposeTiering, setTieringPolicy } from "../../../../../../../lib/nas/tiering.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listTieringProposals({ orgId, shareId: params.shareId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setTieringPolicy({ orgId, shareId: params.shareId, rules: body.rules, legalHoldPaths: body.legalHoldPaths, membership, actorEmail: email }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => proposeTiering({ orgId, shareId: params.shareId, removeLocal: body.removeLocal, membership, actorEmail: email }));
