// app/api/orgs/nas/shares/[shareId]/backup-policy/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getBackupPolicy, setBackupPolicy } from "../../../../../../../lib/nas/backup.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getBackupPolicy({ orgId, shareId: params.shareId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setBackupPolicy({ orgId, shareId: params.shareId, includePaths: body.includePaths, excludePatterns: body.excludePatterns, intervalMinutes: body.intervalMinutes, keepRecoveryPoints: body.keepRecoveryPoints, targetIds: body.targetIds, verify: body.verify, enabled: body.enabled, membership, actorEmail: email }));
