// app/api/orgs/nas/appliances/[applianceId]/disks/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { listDisks } from "../../../../../../../lib/nas/pools.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listDisks({ orgId, applianceId: params.applianceId, membership }));
