// app/api/orgs/nas/threat-events/[eventId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { threatEventAction } from "../../../../../../lib/nas/routeActions.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => threatEventAction({ orgId, eventId: params.eventId, body, membership, actorEmail: email }));
