// app/api/orgs/nas/appliances/[applianceId]/pools/[poolId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../../_lib.js";
import { deletePool, getPoolStatus } from "../../../../../../../../lib/nas/pools.js";
import { poolAction } from "../../../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getPoolStatus({ orgId, poolId: params.poolId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => poolAction({ orgId, poolId: params.poolId, body, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => deletePool({ orgId, poolId: params.poolId, membership, actorEmail: email }));
