// app/api/orgs/nas/appliances/[applianceId]/measure/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { checkApplianceState } from "../../../../../../../lib/nas/health.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => checkApplianceState({ orgId, applianceId: params.applianceId, membership }));
