// app/api/orgs/nas/shares/[shareId]/backup/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { backupShareToInaya, listBackupRuns } from "../../../../../../../lib/nas/backup.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => backupShareToInaya({ orgId, shareId: params.shareId, targetId: body.targetId, verify: body.verify, idempotencyKey: body.idempotencyKey, membership, actorEmail: email }));
export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listBackupRuns({ orgId, shareId: params.shareId, membership }));
