// app/api/orgs/nas/shares/[shareId]/worm/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getWormStatus, setWormPolicy } from "../../../../../../../lib/nas/snapshots.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getWormStatus({ orgId, shareId: params.shareId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setWormPolicy({ orgId, shareId: params.shareId, enabled: body.enabled, retentionDays: body.retentionDays, settleMinutes: body.settleMinutes, mode: body.mode, override: body.override, reason: body.reason, membership, actorEmail: email }));
