// app/api/orgs/nas/appliances/[applianceId]/jobs/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { jobsList } from "../../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => jobsList({ orgId, applianceId: params.applianceId, kind: query.kind, status: query.status, membership }));
