// app/api/orgs/nas/appliances/[applianceId]/state/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { commitNasState, verifyNasState } from "../../../../../../../lib/nas/state.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => verifyNasState({ orgId, applianceId: params.applianceId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => body.commit ? commitNasState({ orgId, applianceId: params.applianceId, membership, actorEmail: email }) : ({ error: 'Send {commit:true} to commit the current state.', status: 400 }));
