// app/api/orgs/nas/shares/[shareId]/access/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { setShareAccess } from "../../../../../../../lib/nas/access.js";

export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setShareAccess({ orgId, shareId: params.shareId, entries: body.entries, hostsAllow: body.hostsAllow, readOnly: body.readOnly, hidden: body.hidden, enabled: body.enabled, reason: body.reason, membership, actorEmail: email }));
