// app/api/orgs/nas/appliances/[applianceId]/lockout-policy/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { setLockoutPolicy } from "../../../../../../../lib/nas/users.js";

export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setLockoutPolicy({ orgId, applianceId: params.applianceId, attempts: body.attempts, durationMinutes: body.durationMinutes, membership, actorEmail: email }));
