// app/api/orgs/nas/appliances/[applianceId]/update-history/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { listUpdates } from "../../../../../../../lib/nas/updates.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listUpdates({ orgId, applianceId: params.applianceId, membership }));
