// app/api/orgs/nas/shares/[shareId]/replication/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { createReplicationPolicy, listReplicationPolicies } from "../../../../../../../lib/nas/replication.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listReplicationPolicies({ orgId, shareId: params.shareId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => createReplicationPolicy({ orgId, shareId: params.shareId, mode: body.mode, targetApplianceId: body.targetApplianceId, targetId: body.targetId, intervalMinutes: body.intervalMinutes, verify: body.verify, membership, actorEmail: email }), { okStatus: 201 });
