// app/api/orgs/nas/tiering/[proposalId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { tieringAction } from "../../../../../../lib/nas/routeActions.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => tieringAction({ orgId, proposalId: params.proposalId, body, membership, actorEmail: email }));
