// app/api/orgs/nas/shares/[shareId]/nfs/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { setNfsExport } from "../../../../../../../lib/nas/shares.js";

export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setNfsExport({ orgId, shareId: params.shareId, enabled: body.enabled, clients: body.clients, readOnly: body.readOnly, rootSquash: body.rootSquash, membership, actorEmail: email }));
