// app/api/orgs/nas/shares/[shareId]/threat/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { listThreatEvents, setThreatPolicy } from "../../../../../../../lib/nas/ransomware.js";
import { threatAction } from "../../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listThreatEvents({ orgId, shareId: params.shareId, state: query.state, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => threatAction({ orgId, shareId: params.shareId, body, membership, actorEmail: email }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setThreatPolicy({ orgId, shareId: params.shareId, enabled: body.enabled, thresholds: body.thresholds, autoSnapshot: body.autoSnapshot, autoLockdown: body.autoLockdown, lockdownMinutes: body.lockdownMinutes, scanIntervalMinutes: body.scanIntervalMinutes, exempt: body.exempt, membership, actorEmail: email }));
