// app/api/orgs/nas/shares/[shareId]/backup/[runId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../../_lib.js";
import { getBackupRun, restoreFromBackup } from "../../../../../../../../lib/nas/backup.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getBackupRun({ orgId, runId: params.runId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => restoreFromBackup({ orgId, shareId: params.shareId, runId: params.runId, relPath: body.relPath, target: body.target, alternateShareId: body.alternateShareId, inPlace: body.inPlace, reason: body.reason, membership, actorEmail: email }));
