// app/api/orgs/nas/users/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../_lib.js";
import { createServiceAccount, listNasUsers, provisionNasUser } from "../../../../../lib/nas/users.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listNasUsers({ orgId, applianceId: query.applianceId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => body.kind === 'service' ? createServiceAccount({ orgId, applianceId: body.applianceId, name: body.name, description: body.description, membership, actorEmail: email }) : provisionNasUser({ orgId, applianceId: body.applianceId, memberEmail: body.memberEmail, membership, actorEmail: email }), { okStatus: 201 });
