// app/api/orgs/nas/shares/[shareId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { deleteShare, getShare } from "../../../../../../lib/nas/shares.js";
import { shareUpdate } from "../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getShare({ orgId, shareId: params.shareId, membership }));
export const PATCH = nasRoute(async ({ orgId, membership, email, query, params, body }) => shareUpdate({ orgId, shareId: params.shareId, body, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => deleteShare({ orgId, shareId: params.shareId, purgeData: query.purge === '1', membership, actorEmail: email }));
