// app/api/orgs/nas/appliances/[applianceId]/locks/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { listLocks } from "../../../../../../../lib/nas/network.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listLocks({ orgId, applianceId: params.applianceId, membership }));
