// app/api/orgs/nas/shares/[shareId]/acl/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getFolderAcl, setFolderAcl } from "../../../../../../../lib/nas/access.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getFolderAcl({ orgId, shareId: params.shareId, relPath: query.relPath, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setFolderAcl({ orgId, shareId: params.shareId, relPath: body.relPath, entries: body.entries, recursive: body.recursive, membership, actorEmail: email }));
