// app/api/orgs/nas/jobs/[jobId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { jobAction } from "../../../../../../lib/nas/routeActions.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => jobAction({ orgId, jobId: params.jobId, action: body.action, membership }));
