// app/api/orgs/nas/appliances/[applianceId]/remote-access/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getRemoteAccess, setRemoteAccess } from "../../../../../../../lib/nas/network.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getRemoteAccess({ orgId, applianceId: params.applianceId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setRemoteAccess({ orgId, applianceId: params.applianceId, mode: body.mode, allowedNetworks: body.allowedNetworks, membership, actorEmail: email }));
