// src/lib/compliance/nist80053.js
//
// Versioned internal catalog of the NIST SP 800-53 Revision 5 BASE controls (Competitive Expansion SOW P2, COMPLIANCE-002), shaped to plug into the existing Regulatory
// Framework Engine (compliance-frameworks.js): static reference data, never editable per organization.
//
// WHAT THIS IS NOT. It is a curated internal subset for organizing controls and evidence: base controls only (no enhancements), the control titles and IDs
// follow NIST SP 800-53 Rev. 5, and each `description` is OUR short paraphrase of the control's purpose. It is NOT the NIST publication, it does NOT carry FedRAMP
// baseline parameter values, and withdrawn controls are omitted. Authoritative text, enhancements and parameters come from NIST SP 800-53 Rev. 5 and the applicable
// FedRAMP baseline. Using this catalog does not make an organization compliant, authorized or certified.

export const CATALOG_ID = "NIST_800_53_R5";
export const CATALOG_VERSION = "internal-2026.1";
export const BASELINE_NOTE = "Internal curated subset of NIST SP 800-53 Rev. 5 base controls. No enhancements, no FedRAMP parameter values. Not the authoritative publication; not a certification.";

export const FAMILIES = {
  AC: "Access Control", AT: "Awareness and Training", AU: "Audit and Accountability", CA: "Assessment, Authorization, and Monitoring", CM: "Configuration Management",
  CP: "Contingency Planning", IA: "Identification and Authentication", IR: "Incident Response", MA: "Maintenance", MP: "Media Protection", PE: "Physical and Environmental Protection",
  PL: "Planning", PM: "Program Management", PS: "Personnel Security", RA: "Risk Assessment", SA: "System and Services Acquisition", SC: "System and Communications Protection",
  SI: "System and Information Integrity", SR: "Supply Chain Risk Management",
};

// family -> [number, title]. "-1" is always "Policy and Procedures" for the family.
const RAW = {
  AC: [[1, "Policy and Procedures"], [2, "Account Management"], [3, "Access Enforcement"], [4, "Information Flow Enforcement"], [5, "Separation of Duties"], [6, "Least Privilege"], [7, "Unsuccessful Logon Attempts"], [8, "System Use Notification"], [9, "Previous Logon Notification"], [10, "Concurrent Session Control"], [11, "Device Lock"], [12, "Session Termination"], [14, "Permitted Actions Without Identification or Authentication"], [16, "Security and Privacy Attributes"], [17, "Remote Access"], [18, "Wireless Access"], [19, "Access Control for Mobile Devices"], [20, "Use of External Systems"], [21, "Information Sharing"], [22, "Publicly Accessible Content"], [23, "Data Mining Protection"], [24, "Access Control Decisions"], [25, "Reference Monitor"]],
  AT: [[1, "Policy and Procedures"], [2, "Literacy Training and Awareness"], [3, "Role-Based Training"], [4, "Training Records"], [6, "Training Feedback"]],
  AU: [[1, "Policy and Procedures"], [2, "Event Logging"], [3, "Content of Audit Records"], [4, "Audit Log Storage Capacity"], [5, "Response to Audit Logging Process Failures"], [6, "Audit Record Review, Analysis, and Reporting"], [7, "Audit Record Reduction and Report Generation"], [8, "Time Stamps"], [9, "Protection of Audit Information"], [10, "Non-repudiation"], [11, "Audit Record Retention"], [12, "Audit Record Generation"], [13, "Monitoring for Information Disclosure"], [14, "Session Audit"], [16, "Cross-organizational Audit Logging"]],
  CA: [[1, "Policy and Procedures"], [2, "Control Assessments"], [3, "Information Exchange"], [5, "Plan of Action and Milestones"], [6, "Authorization"], [7, "Continuous Monitoring"], [8, "Penetration Testing"], [9, "Internal System Connections"]],
  CM: [[1, "Policy and Procedures"], [2, "Baseline Configuration"], [3, "Configuration Change Control"], [4, "Impact Analyses"], [5, "Access Restrictions for Change"], [6, "Configuration Settings"], [7, "Least Functionality"], [8, "System Component Inventory"], [9, "Configuration Management Plan"], [10, "Software Usage Restrictions"], [11, "User-installed Software"], [12, "Information Location"], [13, "Data Action Mapping"], [14, "Signed Components"]],
  CP: [[1, "Policy and Procedures"], [2, "Contingency Plan"], [3, "Contingency Training"], [4, "Contingency Plan Testing"], [6, "Alternate Storage Site"], [7, "Alternate Processing Site"], [8, "Telecommunications Services"], [9, "System Backup"], [10, "System Recovery and Reconstitution"], [11, "Alternate Communications Protocols"], [12, "Safe Mode"], [13, "Alternative Security Mechanisms"]],
  IA: [[1, "Policy and Procedures"], [2, "Identification and Authentication (Organizational Users)"], [3, "Device Identification and Authentication"], [4, "Identifier Management"], [5, "Authenticator Management"], [6, "Authentication Feedback"], [7, "Cryptographic Module Authentication"], [8, "Identification and Authentication (Non-Organizational Users)"], [9, "Service Identification and Authentication"], [10, "Adaptive Authentication"], [11, "Re-authentication"], [12, "Identity Proofing"]],
  IR: [[1, "Policy and Procedures"], [2, "Incident Response Training"], [3, "Incident Response Testing"], [4, "Incident Handling"], [5, "Incident Monitoring"], [6, "Incident Reporting"], [7, "Incident Response Assistance"], [8, "Incident Response Plan"], [9, "Information Spillage Response"], [10, "Integrated Information Security Analysis Team"]],
  MA: [[1, "Policy and Procedures"], [2, "Controlled Maintenance"], [3, "Maintenance Tools"], [4, "Nonlocal Maintenance"], [5, "Maintenance Personnel"], [6, "Timely Maintenance"], [7, "Field Maintenance"]],
  MP: [[1, "Policy and Procedures"], [2, "Media Access"], [3, "Media Marking"], [4, "Media Storage"], [5, "Media Transport"], [6, "Media Sanitization"], [7, "Media Use"], [8, "Media Downgrading"]],
  PE: [[1, "Policy and Procedures"], [2, "Physical Access Authorizations"], [3, "Physical Access Control"], [4, "Access Control for Transmission"], [5, "Access Control for Output Devices"], [6, "Monitoring Physical Access"], [8, "Visitor Access Records"], [9, "Power Equipment and Cabling"], [10, "Emergency Shutoff"], [11, "Emergency Power"], [12, "Emergency Lighting"], [13, "Fire Protection"], [14, "Environmental Controls"], [15, "Water Damage Protection"], [16, "Delivery and Removal"], [17, "Alternate Work Site"], [18, "Location of System Components"], [19, "Information Leakage"], [20, "Asset Monitoring and Tracking"], [21, "Electromagnetic Pulse Protection"], [22, "Component Marking"], [23, "Facility Location"]],
  PL: [[1, "Policy and Procedures"], [2, "System Security and Privacy Plans"], [4, "Rules of Behavior"], [7, "Concept of Operations"], [8, "Security and Privacy Architectures"], [9, "Central Management"], [10, "Baseline Selection"], [11, "Baseline Tailoring"]],
  PM: [[1, "Information Security Program Plan"], [2, "Information Security Program Leadership Role"], [3, "Information Security and Privacy Resources"], [4, "Plan of Action and Milestones Process"], [5, "System Inventory"], [6, "Measures of Performance"], [7, "Enterprise Architecture"], [8, "Critical Infrastructure Plan"], [9, "Risk Management Strategy"], [10, "Authorization Process"], [11, "Mission and Business Process Definition"], [12, "Insider Threat Program"], [13, "Security and Privacy Workforce"], [14, "Testing, Training, and Monitoring"], [15, "Security and Privacy Groups and Associations"], [16, "Threat Awareness Program"], [28, "Risk Framing"], [30, "Supply Chain Risk Management Strategy"], [31, "Continuous Monitoring Strategy"]],
  PS: [[1, "Policy and Procedures"], [2, "Position Risk Designation"], [3, "Personnel Screening"], [4, "Personnel Termination"], [5, "Personnel Transfer"], [6, "Access Agreements"], [7, "External Personnel Security"], [8, "Personnel Sanctions"], [9, "Position Descriptions"]],
  RA: [[1, "Policy and Procedures"], [2, "Security Categorization"], [3, "Risk Assessment"], [5, "Vulnerability Monitoring and Scanning"], [7, "Risk Response"], [8, "Privacy Impact Assessments"], [9, "Criticality Analysis"], [10, "Threat Hunting"]],
  SA: [[1, "Policy and Procedures"], [2, "Allocation of Resources"], [3, "System Development Life Cycle"], [4, "Acquisition Process"], [5, "System Documentation"], [8, "Security and Privacy Engineering Principles"], [9, "External System Services"], [10, "Developer Configuration Management"], [11, "Developer Testing and Evaluation"], [15, "Development Process, Standards, and Tools"], [16, "Developer-provided Training"], [17, "Developer Security and Privacy Architecture and Design"], [21, "Developer Screening"], [22, "Unsupported System Components"]],
  SC: [[1, "Policy and Procedures"], [2, "Separation of System and User Functionality"], [3, "Security Function Isolation"], [4, "Information in Shared System Resources"], [5, "Denial-of-service Protection"], [6, "Resource Availability"], [7, "Boundary Protection"], [8, "Transmission Confidentiality and Integrity"], [10, "Network Disconnect"], [12, "Cryptographic Key Establishment and Management"], [13, "Cryptographic Protection"], [15, "Collaborative Computing Devices and Applications"], [16, "Transmission of Security and Privacy Attributes"], [17, "Public Key Infrastructure Certificates"], [18, "Mobile Code"], [20, "Secure Name/Address Resolution Service (Authoritative Source)"], [21, "Secure Name/Address Resolution Service (Recursive or Caching Resolver)"], [22, "Architecture and Provisioning for Name/Address Resolution Service"], [23, "Session Authenticity"], [24, "Fail in Known State"], [28, "Protection of Information at Rest"], [39, "Process Isolation"], [45, "System Time Synchronization"]],
  SI: [[1, "Policy and Procedures"], [2, "Flaw Remediation"], [3, "Malicious Code Protection"], [4, "System Monitoring"], [5, "Security Alerts, Advisories, and Directives"], [6, "Security and Privacy Function Verification"], [7, "Software, Firmware, and Information Integrity"], [8, "Spam Protection"], [10, "Information Input Validation"], [11, "Error Handling"], [12, "Information Management and Retention"], [13, "Predictable Failure Prevention"], [14, "Non-persistence"], [15, "Information Output Filtering"], [16, "Memory Protection"], [17, "Fail-safe Procedures"], [18, "Personally Identifiable Information Quality Operations"], [19, "De-identification"], [20, "Tainting"], [21, "Information Refresh"], [22, "Information Diversity"], [23, "Information Fragmentation"]],
  SR: [[1, "Policy and Procedures"], [2, "Supply Chain Risk Management Plan"], [3, "Supply Chain Controls and Processes"], [4, "Provenance"], [5, "Acquisition Strategies, Tools, and Methods"], [6, "Supplier Assessments and Reviews"], [7, "Supply Chain Operations Security"], [8, "Notification Agreements"], [9, "Tamper Resistance and Detection"], [10, "Inspection of Systems or Components"], [11, "Component Authenticity"], [12, "Component Disposal"]],
};

const pad = (n) => String(n);
/** Requirement objects in the shape the Regulatory Framework Engine already uses ({ id, title, description }), plus `family`. */
export const REQUIREMENTS = Object.entries(RAW).flatMap(([fam, list]) => list.map(([n, title]) => ({ id: `${fam}-${pad(n)}`, family: fam, title, description: `${FAMILIES[fam]}: ${title.toLowerCase()}. Internal paraphrase for organizing controls and evidence; see NIST SP 800-53 Rev. 5 for the authoritative control text.` })));
export const BY_ID = new Map(REQUIREMENTS.map((r) => [r.id, r]));

export const FRAMEWORK = { id: CATALOG_ID, name: "NIST SP 800-53 Rev. 5 (internal curated catalog)", version: CATALOG_VERSION, requirements: REQUIREMENTS };
export const familyOf = (controlId) => String(controlId).split("-")[0];
