// app/api/orgs/nas/shares/[shareId]/recovery-drill/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { runRecoveryDrill } from "../../../../../../../lib/nas/backup.js";
import { readinessFor } from "../../../../../../../lib/nas/routeActions.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => runRecoveryDrill({ orgId, shareId: params.shareId, runId: body.runId, relativePath: body.relativePath, sampleFiles: body.sampleFiles, membership, actorEmail: email }));
export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => readinessFor({ orgId, shareId: params.shareId, membership }));
