// app/api/orgs/nas/users/[nasUserId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { getNasUserStatus, revokeNasUser } from "../../../../../../lib/nas/users.js";
import { userAction } from "../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getNasUserStatus({ orgId, nasUserId: params.nasUserId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => userAction({ orgId, nasUserId: params.nasUserId, body, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => revokeNasUser({ orgId, nasUserId: params.nasUserId, membership, actorEmail: email }));
