// app/api/orgs/nas/shares/[shareId]/snapshots/[snapshotId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../../_lib.js";
import { browseSnapshot, deleteSnapshot, restoreSnapshot, verifySnapshot } from "../../../../../../../../lib/nas/snapshots.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => query.browse ? browseSnapshot({ orgId, snapshotId: params.snapshotId, relPath: query.relPath, membership }) : verifySnapshot({ orgId, snapshotId: params.snapshotId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => restoreSnapshot({ orgId, snapshotId: params.snapshotId, relPath: body.relPath, inPlace: body.inPlace, reason: body.reason, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => deleteSnapshot({ orgId, snapshotId: params.snapshotId, override: body.override, reason: body.reason, membership, actorEmail: email }));
