// app/api/orgs/nas/shares/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../_lib.js";
import { createShare, listShares } from "../../../../../lib/nas/shares.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listShares({ orgId, applianceId: query.applianceId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => createShare({ orgId, applianceId: body.applianceId, shareName: body.shareName, ownerUnixUser: body.ownerUnixUser, quotaBytes: body.quotaBytes, backend: body.backend, poolId: body.poolId, departmentId: body.departmentId, volumeSizeMb: body.volumeSizeMb, membership, actorEmail: email }), { okStatus: 201 });
