// app/api/orgs/nas/appliances/[applianceId]/groups/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { createNasGroup, listNasGroups } from "../../../../../../../lib/nas/access.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listNasGroups({ orgId, applianceId: params.applianceId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => createNasGroup({ orgId, applianceId: params.applianceId, name: body.name, description: body.description, membership, actorEmail: email }), { okStatus: 201 });
