// app/api/orgs/nas/shares/[shareId]/snapshots/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { createSnapshot, listSnapshots } from "../../../../../../../lib/nas/snapshots.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listSnapshots({ orgId, shareId: params.shareId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => createSnapshot({ orgId, shareId: params.shareId, name: body.name, immutable: body.immutable, retentionDays: body.retentionDays, lockMode: body.lockMode, reason: body.reason, membership, actorEmail: email }), { okStatus: 201 });
