// app/api/orgs/nas/cloud-targets/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../_lib.js";
import { createCloudTarget, listCloudTargets } from "../../../../../lib/nas/cloudTargets.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listCloudTargets({ orgId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => createCloudTarget({ orgId, kind: body.kind, label: body.label, endpoint: body.endpoint, region: body.region, bucket: body.bucket, prefix: body.prefix, accessKeyId: body.accessKeyId, secretAccessKey: body.secretAccessKey, membership, actorEmail: email }), { okStatus: 201 });
