// app/api/orgs/nas/appliances/[applianceId]/compliance/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { complianceReport } from "../../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => complianceReport({ orgId, applianceId: params.applianceId, membership }));
