// app/api/orgs/nas/appliances/[applianceId]/capacity/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getApplianceCapacity } from "../../../../../../../lib/nas/quotas.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getApplianceCapacity({ orgId, applianceId: params.applianceId, membership }));
