// src/lib/admin/dashboard.js
//
// Admin dashboard (Competitive Expansion SOW workstream U, DASH-001). Every tile is computed from records that actually exist, and a tile that
// cannot be answered says so: state OK, ATTENTION (a real issue), NO_DATA (nothing recorded yet), NOT_ENABLED (the feature is off for this
// organization) or UNKNOWN (Inaya does not collect it), with the precise coverage limitation in `note`. Nothing is estimated or filled in.
// Each tile is isolated: one failing query yields UNKNOWN for that tile only. Read access: owner/admin or an auditor.

import { getOrgCollections, toObjectId } from "../orgs.js";
import { hasAdminRole } from "../orgGates.js";
import { isFeatureEnabled } from "../featureFlags.js";

const DAY = 86400_000; const iso = (ms) => new Date(ms).toISOString();
export class DashError extends Error { constructor(status, message) { super(message); this.status = status; } }
const tile = (id, label, base) => ({ id, label, value: null, unit: null, state: "UNKNOWN", note: null, detail: null, ...base });
const ok = (value, extra = {}) => ({ value, state: "OK", ...extra });
const noData = (note) => ({ value: null, state: "NO_DATA", note });
const off = (flag) => ({ value: null, state: "NOT_ENABLED", note: `Turn on ${flag.replace("FEATURE_", "").toLowerCase().replace(/_/g, " ")} under Settings, Beta features to see this.` });
const unknown = (note) => ({ value: null, state: "UNKNOWN", note });

async function guard(id, label, fn) { try { return tile(id, label, await fn()); } catch (e) { return tile(id, label, unknown(`Could not be read right now (${String(e.message || e).slice(0, 80)}).`)); } }

export async function buildDashboard({ orgId, membership, now = Date.now() }) {
  if (!hasAdminRole(membership, ["securityAdmin", "storageAdmin", "complianceAdmin", "dataGovernanceAdmin", "deviceAdmin", "vdrAdmin", "integrationAdmin"], { read: true })) throw new DashError(403, "Only an administrator or auditor can see the dashboard.");
  const c = await getOrgCollections(); const oid = toObjectId(orgId); const db = c.db; const week = iso(now - 7 * DAY); const sid = String(orgId);
  const flag = async (f) => isFeatureEnabled(f, orgId);
  const tiles = await Promise.all([
    guard("storage", "Storage used", async () => { const r = await c.orgDocuments.aggregate([{ $match: { orgId: oid, deletedAt: null } }, { $group: { _id: null, bytes: { $sum: "$sizeBytes" }, files: { $sum: 1 } } }]).toArray(); if (!r[0]?.files) return noData("No files stored yet."); return ok(r[0].bytes, { unit: "bytes", detail: `${r[0].files} files`, note: "Counts current file versions recorded in the workspace and the S3/Azure layer; replicas on storage providers are not added." }); }),
    guard("activeUsers", "People signed in now", async () => { const emails = await c.sessions.distinct("email", { expiresAt: { $gt: iso(now) } }); const members = await c.orgMembers.find({ orgId: oid, status: "active" }).project({ email: 1 }).toArray(); const set = new Set(members.map((m) => m.email)); const n = emails.filter((e) => set.has(e)).length; return n ? ok(n, { detail: `of ${set.size} active members`, note: "People with a live session; last-seen history is not recorded for people without devices." }) : noData("Nobody has a live session."); }),
    guard("externalUsers", "External visitors with access", async () => { const rooms = await c.dataRoomExternalSessions.distinct("externalEmail", { orgId: oid, revokedAt: null, expiresAt: { $gt: iso(now) } }); const shares = await db.collection("drm_sessions").countDocuments({ orgId: sid, expiresAt: { $gt: new Date(now) } }); return rooms.length + shares ? ok(rooms.length, { detail: `${shares} open share-link sessions`, note: "Named data-room visitors; share-link visitors are anonymous so they are counted as sessions." }) : noData("No external visitor has active access."); }),
    guard("shares", "Active share links", async () => { const col = c.documentShares; const active = await col.countDocuments({ orgId: oid, revokedAt: null, expiresAt: { $gt: iso(now) } }); const soon = await col.countDocuments({ orgId: oid, revokedAt: null, expiresAt: { $gt: iso(now), $lt: iso(now + 7 * DAY) } }); return active ? ok(active, { detail: `${soon} expire within 7 days`, state: soon ? "ATTENTION" : "OK" }) : noData("No active share links."); }),
    guard("chats", "Active conversations (7 days)", async () => { if (!(await flag("FEATURE_SECURE_CHAT"))) return off("FEATURE_SECURE_CHAT"); const n = await db.collection("chat_conversations").countDocuments({ $or: [{ orgId: sid }, { orgId: oid }], updatedAt: { $gt: week }, status: "active" }).catch(() => null); if (n == null) return unknown("The chat store could not be queried."); return n ? ok(n, { note: "Counts conversations with activity. Inaya cannot see message content, so nothing about content is shown." }) : noData("No conversation activity in the last 7 days."); }),
    guard("devices", "Devices", async () => { if (!(await flag("FEATURE_DEVICE_CONTROL"))) return off("FEATURE_DEVICE_CONTROL"); const d = db.collection("org_devices"); const total = await d.countDocuments({ orgId: oid }); if (!total) return noData("No device has checked in yet."); const revoked = await d.countDocuments({ orgId: oid, $or: [{ revokedAt: { $exists: true } }, { blockedAt: { $exists: true } }] }); return ok(total, { detail: `${revoked} blocked or removed`, note: "Only devices that have checked in are counted." }); }),
    guard("backup", "Endpoint backup health", async () => { if (!(await flag("FEATURE_ENDPOINT_BACKUP_V2"))) return off("FEATURE_ENDPOINT_BACKUP_V2"); const p = await db.collection("endpoint_backup_profiles").find({ orgId: oid }).toArray(); if (!p.length) return noData("No backup profiles."); const { profileHealth } = await import("../endpoint/backup.js"); const st = p.map((x) => profileHealth(x).state); const bad = st.filter((s) => s === "RED" || s === "AMBER").length; return ok(p.length, { state: bad ? "ATTENTION" : "OK", detail: `${bad} need attention`, note: "Health comes from the runs desktop clients report; a profile that has never run counts as needing attention only once it has a schedule." }); }),
    guard("resilience", "Resilience tests", async () => { const runs = await c.resilienceTestRuns.find({ orgId: oid, startedAt: { $gt: iso(now - 30 * DAY) } }).project({ overallResult: 1 }).toArray(); if (!runs.length) return noData("No resilience test ran in the last 30 days."); const fail = runs.filter((r) => r.overallResult === "FAIL").length; return ok(runs.length, { state: fail ? "ATTENTION" : "OK", detail: `${fail} failed`, note: "Last 30 days." }); }),
    guard("dlp", "DLP decisions (7 days)", async () => { if (!(await flag("FEATURE_DLP"))) return off("FEATURE_DLP"); const rows = await db.collection("dlp_events").aggregate([{ $match: { orgId: oid, at: { $gt: week } } }, { $group: { _id: "$decision", n: { $sum: 1 } } }]).toArray(); const total = rows.reduce((a, r) => a + r.n, 0); return total ? ok(total, { detail: rows.map((r) => `${r.n} ${r._id.toLowerCase().replace(/_/g, " ")}`).join(", "), note: "Only decisions other than a plain allow are recorded." }) : noData("No restrictions applied in the last 7 days."); }),
    guard("classification", "Classification changes (7 days)", async () => { if (!(await flag("FEATURE_SMART_CLASSIFICATION"))) return off("FEATURE_SMART_CLASSIFICATION"); const n = await db.collection("classification_history").countDocuments({ orgId: oid, at: { $gt: week } }); return n ? ok(n) : noData("No classification activity in the last 7 days."); }),
    guard("ransomware", "Open ransomware signals", async () => { if (!(await flag("FEATURE_RANSOMWARE_SIGNALS"))) return off("FEATURE_RANSOMWARE_SIGNALS"); const open = await db.collection("security_signals").find({ orgId: oid, state: "open" }).project({ level: 1 }).toArray(); const contained = await db.collection("ransomware_containments").countDocuments({ orgId: oid, liftedAt: null, until: { $gt: iso(now) } }); return ok(open.length, { state: open.length ? "ATTENTION" : "OK", detail: `${contained} credentials paused`, note: "Signals are heuristics, not proof." }); }),
    guard("audit", "Audit chain integrity", async () => { const { verifyOrgEvidenceIntegrity } = await import("../evidence.js"); const r = await verifyOrgEvidenceIntegrity(orgId); const valid = r?.valid ?? r?.ok; if (valid === undefined) return unknown("The integrity check returned no verdict."); return { value: valid ? "intact" : "broken", state: valid ? "OK" : "ATTENTION", detail: r?.count != null ? `${r.count} entries checked` : null, note: valid ? null : "The hash chain does not verify. Investigate before relying on this audit trail." }; }),
    guard("api", "API keys", async () => { const keys = await c.apiKeys.find({ orgId: oid, revokedAt: null }).project({ lastUsedAt: 1 }).toArray(); if (!keys.length) return noData("No active API keys."); const used = keys.filter((k) => k.lastUsedAt && k.lastUsedAt > week).length; return ok(keys.length, { detail: `${used} used in the last 7 days`, note: "Only the last time each key was used is recorded; per-request counts are not collected." }); }),
    guard("s3", "S3 / Azure request usage", async () => unknown("Request counts are not recorded for the storage API, so no figure is shown. Object changes appear in the audit trail and webhooks.")),
    guard("migrations", "Migration jobs", async () => { const n = await db.collection("s3_migration_jobs").countDocuments({ orgId: oid }).catch(() => 0); return n ? ok(n) : noData("No migration jobs recorded."); }),
    guard("directsync", "DirectSync / desktop backup runs (7 days)", async () => { const runs = await db.collection("endpoint_backup_runs").find({ orgId: oid, at: { $gt: new Date(now - 7 * DAY) } }).project({ status: 1 }).toArray(); if (!runs.length) return noData("No desktop client has reported a run. DirectSync itself does not report status to Inaya yet."); const bad = runs.filter((r) => r.status === "failed").length; return ok(runs.length, { state: bad ? "ATTENTION" : "OK", detail: `${bad} failed` }); }),
    guard("dataRooms", "Data room activity (7 days)", async () => { const n = await c.dataRoomAccessLog.countDocuments({ orgId: oid, accessedAt: { $gt: week } }); const rooms = await c.dataRooms.countDocuments({ orgId: oid, closedAt: null }); return n || rooms ? ok(n, { detail: `${rooms} open rooms` }) : noData("No open rooms and no activity."); }),
    guard("workflows", "Workflow runs (7 days)", async () => { const ex = await c.workflowExecutions.find({ orgId: oid, createdAt: { $gt: week } }).project({ status: 1 }).toArray(); if (!ex.length) return noData("No workflow ran in the last 7 days."); const failed = ex.filter((e) => /FAIL/.test(String(e.status))).length; return ok(ex.length, { state: failed ? "ATTENTION" : "OK", detail: `${failed} failed` }); }),
    guard("issues", "Unresolved security items", async () => {
      const parts = []; const add = (n, t) => { if (n) parts.push({ count: n, text: t }); };
      add(await db.collection("security_signals").countDocuments({ orgId: oid, state: "open" }), "open ransomware signals"); add(await db.collection("dlp_approvals").countDocuments({ orgId: oid, status: "pending" }), "DLP approvals waiting");
      add(await db.collection("governance_policies").countDocuments({ orgId: oid, status: "pending_approval" }), "policies waiting for approval"); add(await db.collection("endpoint_restore_jobs").countDocuments({ orgId: oid, status: "pending_approval" }), "restores waiting for approval");
      add(await db.collection("org_devices").countDocuments({ orgId: oid, blockedAt: { $exists: true }, revokedAt: { $exists: false } }), "blocked devices");
      const total = parts.reduce((a, p) => a + p.count, 0); return ok(total, { state: total ? "ATTENTION" : "OK", detail: parts.map((p) => `${p.count} ${p.text}`).join(", ") || "Nothing is waiting.", note: "Only features that are switched on contribute." });
    }),
  ]);
  return { generatedAt: iso(now), tiles, summary: { attention: tiles.filter((t) => t.state === "ATTENTION").length, noData: tiles.filter((t) => t.state === "NO_DATA").length, unknown: tiles.filter((t) => t.state === "UNKNOWN").length, notEnabled: tiles.filter((t) => t.state === "NOT_ENABLED").length } };
}
