// app/api/orgs/nas/worker/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../_lib.js";
import { workerRun } from "../../../../../lib/nas/routeActions.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => workerRun({ orgId, membership }));
