// app/api/orgs/nas/appliances/[applianceId]/updates/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { applyUpdate, checkForUpdate, setUpdateChannel } from "../../../../../../../lib/nas/updates.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => checkForUpdate({ orgId, applianceId: params.applianceId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => applyUpdate({ orgId, applianceId: params.applianceId, membership, actorEmail: email }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setUpdateChannel({ orgId, applianceId: params.applianceId, channel: body.channel, membership, actorEmail: email }));
