// app/api/orgs/nas/shares/[shareId]/recycle-bin/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { listRecycleBin, purgeRecycleBin, restoreFromRecycleBin, setRecycleRetention } from "../../../../../../../lib/nas/shares.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listRecycleBin({ orgId, shareId: params.shareId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => restoreFromRecycleBin({ orgId, shareId: params.shareId, recyclePath: body.recyclePath, overwrite: body.overwrite, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => purgeRecycleBin({ orgId, shareId: params.shareId, recyclePath: body.recyclePath, olderThanDays: body.olderThanDays, membership, actorEmail: email }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setRecycleRetention({ orgId, shareId: params.shareId, retentionDays: body.retentionDays, membership, actorEmail: email }));
