// app/api/orgs/nas/appliances/[applianceId]/identity/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { identityCapabilities } from "../../../../../../../lib/nas/users.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => ({ capabilities: identityCapabilities() }));
