// app/api/orgs/nas/replication/[policyId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { deleteReplicationPolicy } from "../../../../../../lib/nas/replication.js";
import { replicationAction } from "../../../../../../lib/nas/routeActions.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => replicationAction({ orgId, policyId: params.policyId, body, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => deleteReplicationPolicy({ orgId, policyId: params.policyId, purgeReplica: body.purgeReplica, membership }));
