// app/api/orgs/nas/appliances/[applianceId]/network/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { getNetworkInfo, setDiscovery } from "../../../../../../../lib/nas/network.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => getNetworkInfo({ orgId, applianceId: params.applianceId, membership }));
export const PUT = nasRoute(async ({ orgId, membership, email, query, params, body }) => setDiscovery({ orgId, applianceId: params.applianceId, hostname: body.hostname, mdns: body.mdns, membership, actorEmail: email }));
