// app/api/orgs/nas/appliances/[applianceId]/pools/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { createPool, listPools } from "../../../../../../../lib/nas/pools.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => listPools({ orgId, applianceId: params.applianceId, membership }));
export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => createPool({ orgId, applianceId: params.applianceId, name: body.name, level: body.level, memberSizeMb: body.memberSizeMb, allowFailureInjection: body.allowFailureInjection, membership, actorEmail: email }), { okStatus: 201 });
