// app/api/orgs/nas/groups/[groupId]/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../_lib.js";
import { deleteNasGroup, setNasGroupMember } from "../../../../../../lib/nas/access.js";

export const POST = nasRoute(async ({ orgId, membership, email, query, params, body }) => setNasGroupMember({ orgId, groupId: params.groupId, nasUserId: body.nasUserId, action: body.action, membership, actorEmail: email }));
export const DELETE = nasRoute(async ({ orgId, membership, email, query, params, body }) => deleteNasGroup({ orgId, groupId: params.groupId, membership, actorEmail: email }));
