"use client";

// src/components/business/endpoint/EndpointBackupView.js
//
// Endpoint backup profiles, health, integrity verification and restore (Competitive Expansion SOW G1, ENDPOINT-001/002). The desktop app runs the
// backups and restores; this page defines what to back up and when, shows health from the runs the app reports, verifies a run against what is
// actually stored, and requests restores. A normal profile never deletes backed-up files when a local file disappears: only "mirror" mode does,
// and it needs explicit confirmation.

import { useCallback, useEffect, useState } from "react";
import EmptyState from "../../EmptyState";

const card = "bg-[var(--inaya-overlay-5)] border border-[var(--inaya-overlay-10)] rounded-lg";
const muted = "text-[var(--inaya-text-muted)]";
const btn = "text-[10px] font-bold uppercase bg-[var(--inaya-overlay-5)] border border-[var(--inaya-overlay-10)] px-2 py-1 rounded-lg text-[var(--inaya-text-primary)] hover:bg-[var(--inaya-overlay-10)] disabled:opacity-40";
const accent = "text-[10px] font-bold uppercase px-2.5 py-1 rounded-md bg-[#00f2fe]/10 text-[#00f2fe] border border-[#00f2fe]/30 disabled:opacity-40";
const field = "w-full bg-black/45 border border-[var(--inaya-overlay-15)] rounded-lg px-2 py-1 text-[11px] text-[var(--inaya-text-primary)]";
const when = (iso) => { try { return new Date(iso).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }); } catch { return "-"; } };
const PILL = { GREEN: "text-emerald-400 border-emerald-400/40", AMBER: "text-amber-300 border-amber-400/40", RED: "text-red-400 border-red-400/40", PAUSED: "text-slate-300 border-slate-400/40", NEVER_RUN: "text-slate-300 border-slate-400/40" };
const j = async (path, opts = {}) => { const r = await fetch(path, { credentials: "include", headers: { "Content-Type": "application/json" }, ...opts }); let d = {}; try { d = await r.json(); } catch { /* empty */ } if (!r.ok) throw Object.assign(new Error(d.error || `Request failed (${r.status})`), { status: r.status, data: d }); return d; };
const lines = (v) => String(v || "").split(/\n|,/).map((x) => x.trim()).filter(Boolean);

export default function EndpointBackupView({ orgId, canManage }) {
  const base = "/api/orgs/endpoint-backup"; const [scope, setScope] = useState("mine"); const [profiles, setProfiles] = useState(null); const [jobs, setJobs] = useState([]); const [health, setHealth] = useState(null); const [off, setOff] = useState(false);
  const [err, setErr] = useState(""); const [msg, setMsg] = useState(""); const [open, setOpen] = useState(null); const [runs, setRuns] = useState([]); const [form, setForm] = useState(null); const [rest, setRest] = useState(null);
  const load = useCallback(async () => {
    try { setProfiles((await j(`${base}/profiles?orgId=${orgId}&scope=${scope}`)).profiles); setJobs((await j(`${base}/restore?orgId=${orgId}`)).jobs); if (canManage) setHealth(await j(`${base}/health?orgId=${orgId}`)); setErr(""); }
    catch (e) { if (e.status === 404) setOff(true); else setErr(e.message); }
  }, [orgId, scope, canManage]);
  useEffect(() => { load(); }, [load]);
  const act = async (fn, ok) => { setErr(""); setMsg(""); try { const r = await fn(); if (ok) setMsg(typeof ok === "function" ? ok(r) : ok); load(); return r; } catch (e) { setErr(e.message); } };
  const loadRuns = async (p) => { setOpen(p.profileId); setRuns((await j(`${base}/runs?orgId=${orgId}&profileId=${p.profileId}`).catch(() => ({ runs: [] }))).runs); };
  if (off) return <EmptyState title="Endpoint backup is not enabled" description={canManage ? "Turn on “Endpoint backup profiles” under Settings, Beta features." : "Your organization has not turned on endpoint backup yet."} />;
  const create = () => act(() => j(`${base}/profiles`, { method: "POST", body: JSON.stringify({ orgId, name: form.name, folders: lines(form.folders).map((p) => ({ path: p, include: lines(form.include), exclude: form.exclude.trim() ? lines(form.exclude) : undefined })), schedule: form.mode === "manual" ? { mode: "manual" } : form.mode === "interval" ? { mode: "interval", everyMinutes: Number(form.every) } : { mode: "daily", atHour: Number(form.hour) }, bandwidthKbps: form.bw ? Number(form.bw) : null, retention: { versions: Number(form.versions), days: form.days ? Number(form.days) : null }, bucket: form.bucket, prefix: form.prefix, mode: form.syncMode, confirmMirrorDeletes: form.syncMode === "mirror" ? form.confirm : undefined }) }), "Profile created.").then((r) => r && setForm(null));
  return (
    <div className="space-y-3 text-[12px]">
      <div className="flex flex-wrap gap-2 items-center"><button className={`${btn} ${scope === "mine" ? "!border-[#00f2fe]/40 !text-[#00f2fe]" : ""}`} onClick={() => setScope("mine")}>My profiles</button>{canManage && <button className={`${btn} ${scope === "org" ? "!border-[#00f2fe]/40 !text-[#00f2fe]" : ""}`} onClick={() => setScope("org")}>Everyone</button>}
        <button className={`${accent} ml-auto`} onClick={() => setForm({ name: "", folders: "", include: "", exclude: "", mode: "interval", every: 60, hour: 2, bw: "", versions: 30, days: "", bucket: "endpoint-backups", prefix: "", syncMode: "backup", confirm: false })}>New profile</button></div>
      {err && <p className="text-red-400" role="alert">{err}</p>}{msg && <p className="text-emerald-400" role="status">{msg}</p>}
      {health && scope === "org" && <div className={`${card} p-3`}><p className="font-bold">Backup health</p><p className={muted}>{health.total} profiles: {Object.entries(health.byState).map(([k, v]) => `${v} ${k.toLowerCase().replace("_", " ")}`).join(", ") || "none"}</p>{health.attention.map((a) => <p key={a.profileId}><span className={`text-[10px] font-bold uppercase border rounded-full px-2 py-0.5 mr-1 ${PILL[a.state]}`}>{a.state}</span>{a.name} ({a.person}): {a.reasons[0]}</p>)}</div>}
      {form && <div className={`${card} p-3 space-y-2`}><p className="font-bold">New backup profile</p>
        <div className="grid sm:grid-cols-2 gap-2">
          <input aria-label="Profile name" className={field} placeholder="Name (Documents)" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
          <input aria-label="Bucket" className={field} placeholder="Bucket" value={form.bucket} onChange={(e) => setForm({ ...form, bucket: e.target.value })} />
          <textarea aria-label="Folders" className={field} rows={2} placeholder="Folders to watch (one per line)" value={form.folders} onChange={(e) => setForm({ ...form, folders: e.target.value })} />
          <input aria-label="Prefix" className={field} placeholder="Key prefix in the bucket (optional)" value={form.prefix} onChange={(e) => setForm({ ...form, prefix: e.target.value })} />
          <textarea aria-label="Include patterns" className={field} rows={2} placeholder="Only these patterns (optional): **/*.docx" value={form.include} onChange={(e) => setForm({ ...form, include: e.target.value })} />
          <textarea aria-label="Exclude patterns" className={field} rows={2} placeholder="Skip these patterns (default skips .git, node_modules, temp files)" value={form.exclude} onChange={(e) => setForm({ ...form, exclude: e.target.value })} />
          <div className="flex gap-2 items-center"><select aria-label="Schedule" className={`${field} !w-auto`} value={form.mode} onChange={(e) => setForm({ ...form, mode: e.target.value })}><option value="manual">Manual only</option><option value="interval">Every…</option><option value="daily">Daily at…</option></select>{form.mode === "interval" && <><input aria-label="Minutes" type="number" className={`${field} !w-20`} value={form.every} onChange={(e) => setForm({ ...form, every: e.target.value })} /> minutes</>}{form.mode === "daily" && <><input aria-label="Hour" type="number" min="0" max="23" className={`${field} !w-16`} value={form.hour} onChange={(e) => setForm({ ...form, hour: e.target.value })} /> :00 UTC</>}</div>
          <div className="flex gap-2 items-center"><input aria-label="Bandwidth" type="number" className={`${field} !w-28`} placeholder="Kbps limit" value={form.bw} onChange={(e) => setForm({ ...form, bw: e.target.value })} /><input aria-label="Versions kept" type="number" className={`${field} !w-20`} value={form.versions} onChange={(e) => setForm({ ...form, versions: e.target.value })} /> versions<input aria-label="Days kept" type="number" className={`${field} !w-20`} placeholder="days" value={form.days} onChange={(e) => setForm({ ...form, days: e.target.value })} /></div>
        </div>
        <label className="flex items-center gap-2">Mode <select aria-label="Mode" className={`${field} !w-auto`} value={form.syncMode} onChange={(e) => setForm({ ...form, syncMode: e.target.value })}><option value="backup">Backup (never deletes backed-up files)</option><option value="mirror">Mirror (deletes backed-up files when deleted locally)</option></select></label>
        {form.syncMode === "mirror" && <label className="flex items-center gap-2 text-amber-300"><input type="checkbox" checked={form.confirm} onChange={(e) => setForm({ ...form, confirm: e.target.checked })} /> I understand that mirror mode removes backed-up files when they are deleted on the device.</label>}
        <div className="flex gap-2"><button className={accent} disabled={!form.name || !form.folders.trim()} onClick={create}>Create</button><button className={btn} onClick={() => setForm(null)}>Cancel</button></div></div>}
      {profiles === null ? <p className={muted}>Loading…</p> : profiles.length === 0 ? <EmptyState compact icon="💾" description="No backup profiles yet. Create one, then sign in on the desktop app to run it." /> : profiles.map((p) => (
        <div key={p.profileId} className={`${card} p-3`}>
          <div className="flex flex-wrap items-center gap-2"><b className="text-[13px]">{p.name}</b><span className={`text-[10px] font-bold uppercase border rounded-full px-2 py-0.5 ${PILL[p.health.state]}`}>{p.health.state.replace("_", " ")}</span>{p.mode === "mirror" && <span className="text-[10px] font-bold uppercase text-amber-300">mirror</span>}{scope === "org" && <span className={muted}>{p.email}</span>}</div>
          <p className={`${muted} mt-1`}>{p.folders.map((f) => f.path).join(", ")} → {p.bucket}/{p.prefix} · {p.schedule.mode === "interval" ? `every ${p.schedule.everyMinutes} min` : p.schedule.mode === "daily" ? `daily at ${p.schedule.atHour}:00 UTC` : "manual"}{p.bandwidthKbps ? ` · ${p.bandwidthKbps} Kbps` : ""} · keeps {p.retention.versions} versions{p.retention.days ? ` / ${p.retention.days} days` : ""}</p>
          <p className={muted}>{p.status.lastSuccessAt ? `Last success ${when(p.status.lastSuccessAt)}` : "Never succeeded"}{p.status.changedFiles != null ? ` · ${p.status.changedFiles} changed files` : ""}{p.status.retryQueue ? ` · ${p.status.retryQueue} waiting to retry` : ""}{p.status.lastFailure ? ` · last failure: ${p.status.lastFailure}` : ""}</p>
          {p.health.reasons.length > 0 && <p className="text-amber-300">{p.health.reasons.join(" ")}</p>}
          <div className="flex flex-wrap gap-1 mt-2"><button className={btn} onClick={() => act(() => j(`${base}/profiles/${p.profileId}`, { method: "PATCH", body: JSON.stringify({ orgId, paused: !p.paused }) }), p.paused ? "Resumed." : "Paused.")}>{p.paused ? "Resume" : "Pause"}</button><button className={btn} onClick={() => (open === p.profileId ? setOpen(null) : loadRuns(p))}>Runs</button><button className={btn} onClick={() => setRest({ profile: p, prefix: p.prefix || "", pit: "", target: "original", alt: "", overwrite: false, reason: "" })}>Restore…</button>
            <button className={`${btn} !text-red-400`} onClick={() => window.confirm("Remove this profile? Files already backed up are kept.") && act(() => j(`${base}/profiles/${p.profileId}?orgId=${orgId}`, { method: "DELETE" }), "Profile removed. Backed-up files are kept.")}>Remove</button></div>
          {open === p.profileId && <div className="mt-2">{runs.length === 0 ? <p className={muted}>No runs reported yet.</p> : runs.map((r) => <div key={r.runId} className="flex flex-wrap items-center gap-2 border-t border-[var(--inaya-overlay-10)] py-1"><span className="flex-1">{when(r.at)} · {r.status} · {r.files.changed} changed, {r.files.uploaded} uploaded, {r.files.failed} failed{r.verification ? ` · integrity ${r.verification.result.toLowerCase()} (${r.verification.ok}/${r.verification.checked})` : ""}</span><button className={btn} onClick={() => act(() => j(`${base}/runs/${r.runId}/verify`, { method: "POST", body: JSON.stringify({ orgId, profileId: p.profileId }) }), (v) => `Checked ${v.checked}: ${v.ok} match, ${v.missing} missing, ${v.mismatched} different.`).then(() => loadRuns(p))}>Verify</button></div>)}</div>}
        </div>))}
      {rest && <div className={`${card} p-3 space-y-2`}><p className="font-bold">Restore from “{rest.profile.name}”</p>
        <div className="grid sm:grid-cols-2 gap-2"><input aria-label="Folder to restore" className={field} placeholder="Restore files under this prefix" value={rest.prefix} onChange={(e) => setRest({ ...rest, prefix: e.target.value })} /><input aria-label="Point in time" type="datetime-local" className={field} value={rest.pit} onChange={(e) => setRest({ ...rest, pit: e.target.value })} />
          <select aria-label="Target" className={field} value={rest.target} onChange={(e) => setRest({ ...rest, target: e.target.value })}><option value="original">Back to the original location</option><option value="alternate">To a different folder</option></select>{rest.target === "alternate" && <input aria-label="Alternate folder" className={field} placeholder="Folder path on the device" value={rest.alt} onChange={(e) => setRest({ ...rest, alt: e.target.value })} />}</div>
        <label className="flex items-center gap-2"><input type="checkbox" checked={rest.overwrite} onChange={(e) => setRest({ ...rest, overwrite: e.target.checked })} /> Overwrite files that already exist (otherwise both are kept)</label>{rest.overwrite && <input aria-label="Reason" className={field} placeholder="Reason for overwriting" value={rest.reason} onChange={(e) => setRest({ ...rest, reason: e.target.value })} />}
        <p className={muted}>If unusual file activity is open for this backup, the restore automatically uses a point in time before it and needs a second administrator to approve.</p>
        <div className="flex gap-2"><button className={accent} onClick={() => act(() => j(`${base}/restore`, { method: "POST", body: JSON.stringify({ orgId, profileId: rest.profile.profileId, selection: { prefix: rest.prefix }, pointInTime: rest.pit ? new Date(rest.pit).toISOString() : null, target: rest.target, alternatePath: rest.target === "alternate" ? rest.alt : null, overwrite: rest.overwrite, reason: rest.reason }) }), (r) => `Restore ${r.status.replace("_", " ")}: ${r.files} files.${r.flags.length ? " " + r.flags.join(" ") : ""}`).then((r) => r && setRest(null))}>Request restore</button><button className={btn} onClick={() => setRest(null)}>Cancel</button></div></div>}
      <div className={`${card} p-3`}><p className="font-bold mb-1">Restores</p>{jobs.length === 0 ? <p className={muted}>No restores yet.</p> : jobs.map((r) => <div key={r.jobId} className="flex flex-wrap items-center gap-2 border-t border-[var(--inaya-overlay-10)] py-1"><span className="flex-1">{when(r.createdAt)} · {r.requestedBy} · {r.files} files · {r.target}{r.pointInTime ? ` · as of ${when(r.pointInTime)}` : ""} · <b>{r.status.replace("_", " ")}</b>{r.result ? ` (${r.result.restored} restored, ${r.result.failed} failed)` : ""}{r.flags.map((f) => <span key={f} className="block text-amber-300">{f}</span>)}</span>
        {r.status === "pending_approval" && canManage && <><button className={accent} onClick={() => act(() => j(`${base}/restore/${r.jobId}`, { method: "POST", body: JSON.stringify({ orgId, action: "approve" }) }), "Approved.")}>Approve</button><button className={btn} onClick={() => act(() => j(`${base}/restore/${r.jobId}`, { method: "POST", body: JSON.stringify({ orgId, action: "reject" }) }), "Rejected.")}>Reject</button></>}
        <button className={btn} onClick={async () => { try { const d = await j(`${base}/restore/${r.jobId}?orgId=${orgId}`); const u = URL.createObjectURL(new Blob([d.markdown], { type: "text/markdown" })); const a = document.createElement("a"); a.href = u; a.download = `recovery-report-${r.jobId}.md`; a.click(); URL.revokeObjectURL(u); } catch (e) { setErr(e.message); } }}>Report</button></div>)}</div>
    </div>
  );
}
