// app/api/orgs/nas/appliances/[applianceId]/evidence/route.js -- generated by the NAS API table; thin wrapper over src/lib/nas/*.

import { nasRoute } from "../../../_lib.js";
import { evidenceList } from "../../../../../../../lib/nas/routeActions.js";

export const GET = nasRoute(async ({ orgId, membership, email, query, params, body }) => evidenceList({ orgId, applianceId: params.applianceId, shareId: query.shareId, action: query.action, verify: query.verify === '1', membership }));
