// src/lib/docsApiReference.js
//
// Official Documentation Platform SOW -- hand-authored from the Phase 0
// audit of src/app/api/public/v1/**/route.js (the only route namespace
// designed for third-party integration; see docs/audit/documentation-
// inventory.md for why the other ~509 internal routes aren't documented
// here). No OpenAPI spec exists in this repo to generate from, so this is
// the authoritative source until one exists -- every field below was
// verified against the actual route file, not invented.

export const API_AUTH_NOTE =
  "Every public/v1 request needs Authorization: Bearer <api key>. An org owner/admin issues a key from the Business Workspace's API Keys settings (src/app/api/orgs/api-keys/route.js), or Terraform can be pointed at one via INAYA_API_KEY. The key resolves to exactly one organization server-side (requireApiKey() in src/lib/api-keys.js) -- no request body or query parameter can ever point it at a different org.";

export const API_ENDPOINTS = [
  {
    slug: "evidence",
    method: "GET",
    path: "/api/public/v1/evidence",
    summary: "Fetch the evidence trail for one business record.",
    params: [
      { name: "recordType", in: "query", required: true, description: "The record's type, e.g. INVOICE, PURCHASE_ORDER." },
      { name: "recordId", in: "query", required: true, description: "The record's id." },
    ],
    response: "The record's evidence trail (getEvidenceTrail()) -- the same tamper-evident audit chain data the Business Workspace's own Audit Trail view reads.",
    status: "live",
  },
  {
    slug: "audit-verify",
    method: "GET",
    path: "/api/public/v1/audit/verify",
    summary: "Verify the calling organization's full audit-chain integrity.",
    params: [],
    response: "A pass/fail integrity result over the org's entire audit chain (verifyOrgEvidenceIntegrity()).",
    status: "live",
  },
  {
    slug: "permissions-check",
    method: "GET",
    path: "/api/public/v1/permissions/check",
    summary: "Check whether a named permission gate is enabled for the calling organization.",
    params: [
      { name: "gate", in: "query", required: true, description: "One of 17 gate names, e.g. canManageFinance, canAccessAudit, canManageGovernment -- see orgGates.js for the full list." },
    ],
    response: "{ gate, allowed }. Note: an API key always resolves a synthetic owner-level membership, so this checks that a capability exists and is enabled for the org, not a specific human's individual role.",
    status: "live",
  },
  {
    slug: "storage-resources-list-create",
    method: "GET, POST",
    path: "/api/public/v1/storage/resources",
    summary: "List or create storage resources (volumes / file shares).",
    params: [
      { name: "type", in: "query (GET)", required: false, description: '"volume" or "fileShare".' },
      { name: "tag.<key>", in: "query (GET)", required: false, description: "Any number of tag.<key>=<value> params filter by tag." },
      { name: "type, name, region, capacity, performanceProfile, tags", in: "body (POST)", required: "type, name required", description: "Creates a resource -- see the Storage Control Plane product guide for the full field meanings." },
    ],
    response: "GET: { resources: [...] }. POST: { resource: {...} }.",
    status: "live",
  },
  {
    slug: "storage-resource-detail",
    method: "GET, PATCH, DELETE",
    path: "/api/public/v1/storage/resources/{resourceId}",
    summary: "Read, expand the capacity of, or delete one storage resource.",
    params: [
      { name: "action, newCapacityGB", in: "body (PATCH)", required: true, description: 'action must be "expand"; capacity is increase-only, a decrease is rejected with a 400.' },
    ],
    response: "GET: { resource }. PATCH: { requestedGB }. DELETE: { deleted: true }.",
    status: "live",
  },
  {
    slug: "snapshots-list-create",
    method: "GET, POST",
    path: "/api/public/v1/storage/snapshots",
    summary: "List or create point-in-time snapshots of a storage resource.",
    params: [
      { name: "resourceId", in: "query (GET) or body (POST)", required: "for POST", description: "The source inaya_storage_resource id." },
    ],
    response: "GET: { snapshots: [...] }. POST: { snapshot: {...} } -- a real, incremental, independently-verifiable capture; see the Storage Control Plane guide.",
    status: "live",
  },
  {
    slug: "snapshot-detail",
    method: "GET, DELETE",
    path: "/api/public/v1/storage/snapshots/{snapshotId}",
    summary: "Read or delete one snapshot.",
    params: [],
    response: "GET: { snapshot }. DELETE: { deleted: true }.",
    status: "live",
  },
  {
    slug: "backup-policies-list-create",
    method: "GET, POST",
    path: "/api/public/v1/storage/backup-policies",
    summary: "List or create a tag-selector-scoped automated backup policy.",
    params: [
      { name: "name, tagSelector, notificationPolicy", in: "body (POST)", required: "name required", description: 'tagSelector is a {key: value} map; notificationPolicy is "onFailure" (default), "always", or "never".' },
    ],
    response: "GET: { policies: [...] }. POST: { policy: {...} }.",
    status: "live",
  },
  {
    slug: "backup-policy-detail",
    method: "GET, PATCH, DELETE",
    path: "/api/public/v1/storage/backup-policies/{policyId}",
    summary: "Read, pause/resume, or delete one backup policy.",
    params: [
      { name: "enabled", in: "body (PATCH)", required: true, description: "true to resume, false to pause." },
    ],
    response: "GET: { policy }. PATCH: { policy }. DELETE: { deleted: true } (soft delete).",
    status: "live",
  },
  {
    slug: "backup-plans-list-create",
    method: "GET, POST",
    path: "/api/public/v1/storage/backup-plans",
    summary: "List or create a schedule + retention rule under a backup policy.",
    params: [
      { name: "policyId", in: "query (GET)", required: false, description: "Filter to one policy's plans." },
      { name: "policyId, frequency, retentionCount, priority", in: "body (POST)", required: "policyId, frequency, retentionCount required", description: 'frequency is one of daily/weekly/monthly/longTerm.' },
    ],
    response: "GET: { plans: [...] } (each with a computed health field). POST: { plan: {...} }.",
    status: "live",
  },
  {
    slug: "backup-plan-detail",
    method: "GET, DELETE",
    path: "/api/public/v1/storage/backup-plans/{planId}",
    summary: "Read or delete one backup plan.",
    params: [],
    response: "GET: { plan } (with health). DELETE: { deleted: true } (soft delete).",
    status: "live",
  },
  // ---- Customer Portal & Customer Service (support API keys: Business Workspace > Customer Support > Settings > API keys) ----
  {
    slug: "support-tickets",
    method: "GET, POST",
    path: "/api/public/v1/support/tickets",
    summary: "List a customer's tickets or create one. Needs a support API key with tickets:read / tickets:write.",
    params: [
      { name: "customerEmail, status, limit, skip", in: "query (GET)", required: false, description: "customerEmail is only used by a service (unbound) key; a customer-bound key always acts as its own customer. status is open or resolved." },
      { name: "subject, description, type, category, customerEmail, linkedInvoiceNumber", in: "body (POST)", required: "subject, description required", description: "customerEmail is required for a service key and forbidden to differ from the bound customer for a bound key. Send an Idempotency-Key header (8-100 characters): a retry returns the first ticket instead of creating another. Priority is decided by policy, not by the caller." },
    ],
    response: "GET: { tickets: [...], total }. POST: 201 { ticket, duplicate } in the customer-safe shape (public messages and customer-facing status only).",
    status: "live",
  },
  {
    slug: "support-ticket-detail",
    method: "GET",
    path: "/api/public/v1/support/tickets/{ticketId}",
    summary: "Read one ticket as its customer would see it.",
    params: [],
    response: "{ ticket } with public messages, attachments and the customer-facing status. Internal notes, routing, SLA internals and AI output are never included. A ticket the key may not see is a 404.",
    status: "live",
  },
  {
    slug: "support-ticket-replies",
    method: "POST",
    path: "/api/public/v1/support/tickets/{ticketId}/replies",
    summary: "Add a customer reply to a ticket (tickets:write).",
    params: [{ name: "body", in: "body (POST)", required: true, description: "Plain text. Markup is not stored." }],
    response: "201 { message }. A reply on a closed ticket is refused (409) with a path to a follow-up request; a reply on a solved ticket reopens it.",
    status: "live",
  },
  {
    slug: "support-ticket-close",
    method: "POST",
    path: "/api/public/v1/support/tickets/{ticketId}/close",
    summary: "Mark a ticket resolved on behalf of its customer (tickets:write).",
    params: [],
    response: "{ ticket } with the customer-facing status SOLVED. The customer may reopen it inside the reopen window.",
    status: "live",
  },
  {
    slug: "support-ticket-reopen",
    method: "POST",
    path: "/api/public/v1/support/tickets/{ticketId}/reopen",
    summary: "Reopen a solved ticket (tickets:write).",
    params: [{ name: "reason", in: "body (POST)", required: false, description: "Short text recorded in the audit trail." }],
    response: "{ ticket }.",
    status: "live",
  },
  {
    slug: "support-ticket-attachments",
    method: "POST",
    path: "/api/public/v1/support/tickets/{ticketId}/attachments",
    summary: "Attach a file to a ticket (attachments:write).",
    params: [{ name: "filename, contentBase64", in: "body (POST)", required: true, description: "Up to 4 MB after decoding. Executables and scripts are refused; files are stored encrypted and are policy-checked only (there is no antivirus engine)." }],
    response: "201 { attachment: { id, filename, contentType, sizeBytes } }.",
    status: "live",
  },
  {
    slug: "support-knowledge",
    method: "GET",
    path: "/api/public/v1/support/knowledge",
    summary: "Search published knowledge-base articles a customer may read (knowledge:read).",
    params: [{ name: "q, limit", in: "query (GET)", required: false, description: "Search text and result count." }],
    response: "{ results: [{ slug, title, summary, snippet }] }. Read one article at /api/public/v1/support/knowledge/{slug}.",
    status: "live",
  },
  {
    slug: "support-invoices",
    method: "GET",
    path: "/api/public/v1/support/invoices",
    summary: "Read-only list of the customer's invoices from your Finance records (invoices:read).",
    params: [{ name: "customerEmail", in: "query (GET)", required: false, description: "Service keys only." }],
    response: "{ invoices: [{ invoiceNumber, issueDate, dueDate, status, currency, total }] }. Only the customer's own CRM contact is ever read; nothing is copied.",
    status: "live",
  },
  {
    slug: "support-queues",
    method: "GET",
    path: "/api/public/v1/support/queues",
    summary: "List active queue names (queues:read).",
    params: [],
    response: "{ queues: [{ id, name, description }] }.",
    status: "live",
  },
  {
    slug: "support-ideas",
    method: "POST",
    path: "/api/public/v1/support/ideas",
    summary: "Submit an idea on behalf of a bound customer (ideas:write; customer-bound keys only).",
    params: [{ name: "title, description, expectedBenefit, communityVisible", in: "body (POST)", required: "title, description required", description: "Ideas are private unless the organization enables voting and the customer opts in." }],
    response: "201 { idea }.",
    status: "live",
  },
  {
    slug: "support-ai-chat",
    method: "POST",
    path: "/api/public/v1/support/ai/chat",
    summary: "Ask the AI assistant a question as a bound customer (ai:chat).",
    params: [{ name: "message, sessionId", in: "body (POST)", required: "message required", description: "The assistant answers only from published articles the customer may read and cites them. If it cannot answer, handoffOffered is true." }],
    response: "{ sessionId, reply: { text, citations, handoffOffered } }.",
    status: "live",
  },
  {
    slug: "support-events",
    method: "GET",
    path: "/api/public/v1/support/events",
    summary: "Ordered feed of support events for a service key (events:read).",
    params: [{ name: "since, limit", in: "query (GET)", required: false, description: "ISO timestamp cursor and page size (max 200)." }],
    response: "{ events: [{ id, type, createdAt, ticketId, data }] }.",
    status: "live",
  },
  {
    slug: "support-uploads",
    method: "POST",
    path: "/api/public/v1/support/uploads",
    summary: "Start a large attachment upload (attachments:write). Files up to 25 MB are sent in 3 MB chunks.",
    params: [{ name: "ticketId, filename, size, sha256", in: "body (POST)", required: "ticketId, filename, size required", description: "Type and size are checked before any bytes are sent. sha256 (hex) is optional and, when given, verified after assembly." }],
    response: "{ uploadId, chunkBytes, chunks, filename }. Then PUT /api/public/v1/support/uploads/{uploadId}?index=N with the raw bytes of chunk N (chunkBytes each, the last one shorter), and POST /api/public/v1/support/uploads/{uploadId} to assemble, scan and store the file. A file that fails the malware scan is refused with reasonCode MALWARE_DETECTED.",
    status: "live",
  },
  {
    slug: "support-upload-chunk",
    method: "PUT, POST",
    path: "/api/public/v1/support/uploads/{uploadId}",
    summary: "Send one chunk (PUT ?index=N) or complete the upload (POST).",
    params: [{ name: "index", in: "query (PUT)", required: true, description: "Zero-based chunk number. Re-sending a chunk is harmless." }],
    response: "PUT: { received: N }. POST: { attachment: { id, filename, contentType, sizeBytes } }, or 409 with the list of chunks received if some are missing.",
    status: "live",
  },
];
