// src/lib/evidencePdf.js
//
// Renders the evidence package (evidenceExporter.js) as a PDF using
// pdfkit -- a pure-JS renderer with no headless-browser dependency, so it
// runs in Inaya's actual serverless deployment target the same way it
// runs locally (unlike puppeteer-core, which this repo's OTHER PDF
// generators use for offline scripts run on a real machine with Chrome
// installed -- not viable inside a Vercel function).

import PDFDocument from "pdfkit";

function heading(doc, text) {
  doc.moveDown(0.5).fontSize(14).fillColor("#0a5f6e").text(text, { underline: false });
  doc.fillColor("#000000").fontSize(10);
}

function kv(doc, label, value) {
  doc.fontSize(9).fillColor("#555555").text(label, { continued: true }).fillColor("#000000").text(` ${value ?? "—"}`);
}

export function renderEvidencePdf(pkg) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#12161f").text("Inaya Compliance Evidence Package", { align: "left" });
    doc.moveDown(0.3).fontSize(9).fillColor("#777777").text("Generated evidence, not a compliance certification.");
    doc.fillColor("#000000");

    heading(doc, "Executive Summary");
    kv(doc, "Organization:", pkg.executiveSummary.organization);
    kv(doc, "Export timestamp:", pkg.executiveSummary.exportTimestamp);
    kv(doc, "Reporting period:", `${pkg.executiveSummary.reportingPeriod.since || "beginning of record"} — ${pkg.executiveSummary.reportingPeriod.until}`);
    kv(doc, "Generated by:", pkg.executiveSummary.generatedByEmail);

    heading(doc, "Storage Evidence");
    if (pkg.storageEvidence.buckets.length === 0) {
      doc.fontSize(9).text("No buckets on record for this organization.");
    }
    for (const b of pkg.storageEvidence.buckets) {
      doc.fontSize(9).fillColor("#000000").text(`• ${b.bucket}`, { continued: false });
      doc.fontSize(8).fillColor("#555555").text(
        `   Versioning: ${b.versioningStatus}   Object Lock: ${b.objectLockEnabled ? "Enabled" : "Disabled"}   Lifecycle rules: ${b.lifecycleRules.length}`
      );
    }
    doc.fillColor("#000000");

    heading(doc, "Security Evidence");
    kv(doc, "Authentication/authorization/credential events in scope:", pkg.securityEvidence.eventCount);

    heading(doc, "Audit Evidence");
    kv(doc, "Audit chain entries in scope:", pkg.auditEvidence.entryCount);
    kv(doc, "Chain integrity verification:", pkg.auditEvidence.chainIntegrity.valid ? `VALID (${pkg.auditEvidence.chainIntegrity.count} entries verified)` : `BROKEN at seq ${pkg.auditEvidence.chainIntegrity.brokenAtSeq} — ${pkg.auditEvidence.chainIntegrity.reason}`);

    heading(doc, "Cryptographic Evidence");
    kv(doc, "Encryption model:", pkg.cryptographicEvidence.encryptionModel);
    kv(doc, "Audit chain algorithm:", pkg.cryptographicEvidence.auditChainAlgorithm);

    heading(doc, "Export Integrity");
    doc.fontSize(8).font("Courier").text(`SHA-256: ${pkg.exportHash}`);
    doc.font("Helvetica");

    doc.moveDown(1).fontSize(8).fillColor("#777777").text(pkg.disclosure, { align: "left" });

    doc.end();
  });
}
